# docker-compose.yml
version: "3"
services:
  app:
    image: node-app
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 5000
    ports:
      - "5000:5000"

  redis:
      image: redis:latest
      ports:
        - "6379:6379"

  postgres:
    image: postgres
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db